# git ignores
ignores:
  - Thumbs.db
  - .DS_Store
  - '*.swp'
  - themes/
  - _issues.json

# cli commands
commands:
  - version
  - init
  - build
  - server
  - clean

# files keeps
keeps:
  - themes
  - scripts
  - config.yml
  - CNAME
  - README.md
  - LICENSE
  - _issues.json
  - favicon.ico
  - package.json
  - package-lock.json
  - node_modules
