# git ignores
ignores:
  - Thumbs.db
  - .DS_Store
  - '*.swp'
  - themes/

# files keeps
keeps:
  - themes
  - scripts
  - config.yml
  - CNAME
  - README.md
  - LICENSE
  - .gitignore
  - package.json
  - package-lock.json
  - node_modules
  - .git
