
# site
title: AcyOrt
url: http://yoursite.com
description: A Node.js blog tool powered by GitHub.
rss: rss.xml

# theme
theme: ccc45

# pagination
per_page: 2

# menu
menu:
  - name: home
    url: /
  - name: about
    url: /about
  - name: archives
    url: /archives

# category
default_category: uncategorized

# comment
duoshuo:
disqus:

# site post authors filter
authors:
  - LoeiFy
  - author0
  - author1

# site content issue
# username/repository
issue_repo: AcyOrt/acyort.github.io

# site publish directory
public_dir: public

# GitHub access token(Optional)
# token should be separated by whitespace

# token: sd46a6d65a asd8sdbn
