
# site
title: AcyOrt
description: A Node.js blog tool powered by GitHub. 
rss: rss.xml

# site url. you can set as 'http://yoursite.com/child' if need
# please add 'http://' or 'https://'
url: http://acyort.github.io/test

# theme
theme: ccc45

# pagination
per_page: 3
archives_per_page: 30

#menu
menu:
    home: /
    about: /about
    archives: /archives
    tags: /tags
    categories: /categories

# category
default_category: uncategorized

# html output directory or child directory e.g. 'child'
public_dir: /test

# comment
duoshuo:
disqus: acyort

# site content issue
# username/repository
issue_repo: AcyOrt/acyort.github.io

# thumbnail mode 
# 1: use the first image as thumbnail and remove the image
# 2: use the first image as thumbnail but not remove the image
thumbnail_mode: 2

# thumbnail size
# whether to get the thumbnail size
thumbnail_size: false

# site post authors filter
authors:
    - LoeiFy
    - author0
    - author1

# custom fields
customs: 
    - test
    - title

# GitHub access token(Optional)
# token should be separated by whitespace if you push this file to GitHub 
# token: sd46a6d65a asd8sdbn

# dev mode
dev: true
