# site
title: AcyOrt
description: A Node.js blog tool powered by GitHub.
keywords: acyort, nodejs, blog
rss: rss.xml
favicon: icon.png

# site url. you can set as 'http://yoursite.com/child' if need
# please add 'http://' or 'https://'
url: http://acyort.github.io

# comment
disqus: acyort
duoshuo:

# theme
theme: ccc45

# pagination
per_page: 3
archives_per_page: 30

#menu
menu:
    home: /
    about: /about
    archives: /archives
    tags: /tags
    categories: /categories

# category
default_category: uncategorized

# html output directory or child directory e.g. 'child'
public_dir:

# category directory
category_dir:

# tag directory
tag_dir:

# post directory
post_dir:

# archives directory
archives_dir:

# site content source
# your github username/repository
# username
user: AcyOrt
# repository
repository: acyort.github.io

# thumbnail mode
# 1: use the first image as thumbnail and remove the image
# 2: use the first image as thumbnail but not remove the image
thumbnail_mode: 2

# site post authors filter
authors:
#    - LoeiFy
#    - author0
#    - author1

# GitHub access token(optional)
# token should be separated by '#' if you push this file to GitHub
# token: s#d46a6d65aasd8sdbn

# json output
json: false

# dev mode
# boolean or string
# you can set test json path: test/test.json
dev: false
