# url of website. format like http://<domain>/<path> or https://<domain>
url:

# website template
template: ccc45

# scripts, script file name
scripts:
  # - active.js

# plugins, npm modules
plugins:
  # - xxx module

# output, where static site files located
public_dir: /

# timezone, website timezone. use machine setting by default
# example: `America/New_York`, `Japan`, `UTC`, or `Asia/Shanghai`
timezone:

# language of website
language: en
