# site
# default "AcyOrt", "A Node.js blog tool powered by GitHub."
title:
description:

# rss
# set false if no need rss output
# default "rss.xml"
rss:

# site url. you can set as 'http://yoursite.com/child' if need
# please add 'http://' or 'https://'
# default "https://acyortjs.github.io"
url:

# language
# base on the theme support
# default "en"
language:

# theme
# default "ccc45"
theme:

# pagination
# set 0 if no need paging
# default 10, 30
per_page: 3
archives_per_page: 3

# thumbnail mode
# 1: use the first image as thumbnail and remove the image
# 2: use the first image as thumbnail but not remove the image
# default 2
thumbnail_mode:

# menu
menu:
  # archives: /archives/
  # categories: /category/
  # tags: /tag/

# category
# default "uncategorized"
default_category:

# html output directory or child directory e.g. 'child'
# default "/"
public_dir:

# category directory
# default "category"
category_dir:

# tag directory
# default "tag"
tag_dir:

# post directory
# default "posts"
post_dir:

# archives directory
# default "archives"
archives_dir:

# site content source
# your github user/repository
# default "acyortjs", "acyortjs.github.io"
user: LoeiFy
repository: Recordum

# post authors
# github username
authors:
#  - author0
#  - author1

# gitHub access token(optional)
# token should be separated by '#' if you push this file to github
# token: s#d46a6d65aasd8sdbn

# json output
# boolean or string
# you can set json output path
# default false
json: json

# dev mode
# default false
dev:

# other
# customize some settings if need

# disqus:
# keywords:
# favicon:
