# site
title:
description:
keywords:
rss: rss.xml
favicon:

# site url. you can set as 'http://yoursite.com/child' if need
# please add 'http://' or 'https://'
url:

# comment
disqus:

# language
language: zh-CN

# theme
theme: ccc45

# pagination
# set 0 if no need paging
per_page: 5
archives_per_page: 30

# thumbnail mode
# 1: use the first image as thumbnail and remove the image
# 2: use the first image as thumbnail but not remove the image
thumbnail_mode: 2

#menu
menu:
  archives: /archives
  categories: /categories
  tags: /tags
  about: /pages/about

# category
default_category: uncategorized

# html output directory or child directory e.g. 'child'
# default "/"
public_dir:

# category directory
# default "category"
category_dir:

# tag directory
# default "tag"
tag_dir:

# post directory
# default "posts"
post_dir:

# archives directory
# default "archives"
archives_dir:

# site content source
# your github username/repository
user:
repository:

# post authors
# github username
authors:
#  - author0
#  - author1

# GitHub access token(optional)
# token should be separated by '#' if you push this file to GitHub
# token: s#d46a6d65aasd8sdbn

# json output
# boolean or string
# you can set json output path
json: false

# dev mode
dev: false

# other
# customize some settings if you need

# duoshuo:
# blogroll:
#  GitHub: https://github.com
